### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by adriatic** [MikeWasson/LocalAccountsApp#1]
Hi Mike

It seems that we are rowing in the same direction with a similar pace, as I am finding answers to all of my questions by looking at your most recent work - this one in particular :-)

My use case is slightly different from your app here - as I would like to see how another app (assume a server application) authenticates itself to LocalAccountsApp and exchanges data with it, using Web Services API. This "peer-server" application would have its account with LocalAccountsApp and uses https (SSL) protocol.

If you are in the mood to discuss some details of such modified example, I would be happy to write it using your existing code and give it back to you, to enrich your collection of samples

**Comment by adriatic** [comment]
Interesting case: no response for almost four years and then a silent close 😏

**Comment by VeronicaWasson** [comment]
Yeah apologies about that but since I hadn't answered in 2014 - 2017, I figured I should just close the issue. 🙁 I'm currently not working much with ASP.NET, so I'm not even up on how ASP.NET Core handles local authentication.

**Comment by adriatic** [comment]
When I got the email notice from GitHub, my reaction was:
- who the hell is Mike Wasson?
- why am I getting this notice?
- what is LocalAccountsApp?

only then did I realize how I solved this (and other similar situation) using Auth0 - and that I still have no recollection of posting this issue.

**Comment by VeronicaWasson** [comment]
😸
