### ISSUE TITLE
Cookie authentication in ApplicationOAuthProvider.GrantResourceOwnerCredentials

### ISSUE THREAD

**Issue by flyfishMT** [MikeWasson/LocalAccountsApp#2]
Why do you perform Cookie Authentication in ApplicationOAuthProvider.GrantResourceOwnerCredentials?  This seems strange to me since it is the "OAuth Provider." But I am finding I may have to do the same thing as I can't find a better way to allow cookie auth for MVC when using OAuth for WebApi.  Great work - thanks!

**Comment by VeronicaWasson** [comment]
After the user signs in, the credentials are stored in a cookie, so the user doesn't have to sign in each time. Cookie authentication is to authenticate via the cookie.
